### ISSUE TITLE
Could you mention in the README that Python3 is necessary for this to run?

### ISSUE THREAD

**Issue by Jane333** [fzyukio/multidimensional-variable-length-seq2seq-autoencoder#1]
Hello,

thank you for publishing this code! I've been looking for an easy-to-use variable length TensorFlow autoencoder, and this one seems to do exactly what I need.

Would you consider mentioning in the README that the code requires Python 3.x? It took me a while to figure out based on the error messages; also, the `"if PY3:"` part in `main.py` was a bit misleading, as I thought both Python versions would work.

For example, in `lr_classes.py`, `class LRFunc():` had to be changed to `class LRFunc(object):`. Also, the `scipy` and `matplotlib` versions in `requirements.txt` were not available on my system for Python 2.x. Then there were some other errors, at which point I switched to Python 3.

Thanks!

**Comment by fzyukio** [comment]
Thanks for the feedback. I did try to make it p2 and p3 compatible but obviously I missed some.

**Comment by fzyukio** [comment]
Should be py2 compatible now.

**Comment by RedQueen76** [comment]
> 
Hello, 
I am using python 3.6, it reports ImportError: cannot import name 'SIGUSR1', I would like to ask which version of python3 are you using? Thanks

**Comment by seekeren** [comment]
> Hello,
> 
> thank you for publishing this code! I've been looking for an easy-to-use variable length TensorFlow autoencoder, and this one seems to do exactly what I need.
> 
> Would you consider mentioning in the README that the code requires Python 3.x? It took me a while to figure out based on the error messages; also, the `"if PY3:"` part in `main.py` was a bit misleading, as I thought both Python versions would work.
> 
> For example, in `lr_classes.py`, `class LRFunc():` had to be changed to `class LRFunc(object):`. Also, the `scipy` and `matplotlib` versions in `requirements.txt` were not available on my system for Python 2.x. Then there were some other errors, at which point I switched to Python 3.
> 
> Thanks!

Hello,
I am using python 3.6, it reports ImportError: cannot import name 'SIGUSR1', I would like to ask which version of python3 are you using? Thanks
